{% set version = "0.2.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-cropcircles
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/cropcircles_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/cropcircles/cropcircles_{{ version }}.tar.gz
  sha256: 8b7fe6b21e6831903534e5a4cb9cc69802f909dfeee0089b19726cde31e0f1bd

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-glue
    - r-magick
    - r-purrr
  run:
    - r-base
    - r-glue
    - r-magick
    - r-purrr

test:
  commands:
    - $R -e "library('cropcircles')"           # [not win]
    - "\"%R%\" -e \"library('cropcircles')\""  # [win]

about:
  home: https://github.com/doehm/cropcircles
  license: MIT
  summary: Images are cropped to a circle with a transparent background. The function takes a vector of images, either local or from a link, and circle crops the image. Paths to the cropped image are returned for plotting with 'ggplot2'.
  license_family: CC

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE
extra:
  recipe-maintainers:
    - conda-forge/r
